Update README.md
DevRel-Foundation/.github pull request #13
Opened 2024-08-20 14:32 UTC by anajsana

include "what is a Steering Committee" and volunteer SC term

2024-08-20 14:36 UTC, leggetter requested changes
A few small change requests

2024-08-20 14:36 UTC, leggetter commented on profile/README.md
> +  There is currently a temporary Volunteer Steering Committee. We, the volunteer Steering Committe participants, are composed of tenured Developer Relations professionals, who initiated this “intent
```suggestion
  There is currently a temporary Volunteer Steering Committee. We, the volunteer Steering Committee participants, are composed of tenured Developer Relations professionals who initiated this “intent to form foundation” built through the LF’s guidance and principles. A new leadership will be established once the charter and mission are in place. This process will be via elections at a future date to be determined.
```

2024-08-20 14:36 UTC, leggetter commented on profile/README.md
> +  While our profession is relatively small, it is big enough that there are many really good people who can do this work. And we hope they want to! We had the initiative and time to do this, and so w
```suggestion
  While our profession is relatively small, it is big enough that there are many really good people who can do this work. And we hope they want to! We had the initiative and time to do this, and so we feel it’s reasonable for us, just like anyone else, to take the first steps forward on building something
```

2024-08-26 08:03 UTC, anajsana commented
> A few small change requests

thanks! I've just committed your changes and made a few edits re FAQ section:

- Added a few edits on the "what is an SC" using the wording from the CHAOSS governance as a reference in their [governing board section](https://chaoss.community/governance/)

- Added a new question for those new to OS projects called "What is a charter" and be explicit that charters are living documents and can have multiple versions in the future, as the project evolves

2024-08-27 18:38 UTC, jcleblanc requested changes
The content lgtm with the exception of some small tweaks to line 66: 
"There is currently a temporary Steering Committee...." as the "temporary" was raised as a confusing point in our last meeting. 

I'd recommend dropped that and instead just stating:
"The current Steering Committee participants are composed of tenured Developer Relations professionals who initiated this “intent to form foundation” built through the LF’s guidance and principles. A new leadership will be established once the charter and mission are in place. This process will be via elections at a future date to be determined."

2024-08-27 19:00 UTC, anajsana commented on profile/README.md
> +  There is currently a temporary Steering Committee. We, the Steering Committee participants, are composed of tenured Developer Relations professionals who initiated this “intent to form foundation”
```suggestion
 The current Steering Committee participants are composed of tenured Developer Relations professionals who initiated this “intent to form foundation” built through the LF’s guidance and principles. A new leadership will be established once the charter and mission are in place. This process will be via elections at a future date to be determined.
```

2024-08-27 19:03 UTC, anajsana commented
> The content lgtm with the exception of some small tweaks to line 66: 
> 
> "There is currently a temporary Steering Committee...." as the "temporary" was raised as a confusing point in our last meeting. 
> 
> 
> 
> I'd recommend dropped that and instead just stating:
> 
> "The current Steering Committee participants are composed of tenured Developer Relations professionals who initiated this “intent to form foundation” built through the LF’s guidance and principles. A new leadership will be established once the charter and mission are in place. This process will be via elections at a future date to be determined."
> 
> 
> 
> 

Thanks for your review ! I've made the requested changes in line 66 based on your comment 🙂

2024-08-27 21:37 UTC, jcleblanc approved these changes
lgtm; thanks!

2024-08-27 22:52 UTC, Cruzn65 commented
Thank you. Please remove Temporary or Interim from Github as I think I saw it elsewhere. CheerS!

2024-08-28 06:07 UTC, merged